name: "MA District 10"
description: "Marijuana Anonymous District 10 - Los Angeles East"
markdown: rdiscount
pygments: true
permalink: post/:year/:month-:day/:title
paginate: 3
paginate_path: "news/:num"
excerpt_separator: <!-- more -->
exclude: [assets, node_modules, saas, CNAME, Gruntfile.js, package.json, README.md]
abs_url: http://madistrict10.org
#baseurl: 
timezone: America/Los_Angeles
excerpt_separator: <!--more-->
