name: RedTeamDesign
markdown: rdiscount
pygments: true
permalink: /:title
paginate: 10
excerpt_separator: <!-- more -->
baseurl: http://www.red-team-design.com
exclude: [rtd.sublime-project, rtd.sublime-workspace, CNAME, Gruntfile.js, package.json, README.md]